.\"
.\" Copyright (c) 2014 Franco Fichtner <franco@packetwerk.com>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd October 26, 2014
.Dt PEAK_AUDIT 3
.Os
.Sh NAME
.Nm peak_audit_add ,
.Nm peak_audit_get ,
.Nm peak_audit_inc ,
.Nm peak_audit_name ,
.Nm peak_audit_set ,
.Nm peak_audit_sync
.Nd runtime counters
.Sh SYNOPSIS
.In peak.h
.Ft void
.Fn peak_audit_add "const unsigned int field" "const uint64_t value"
.Ft uint64_t
.Fn peak_audit_get "const unsigned int field"
.Ft void
.Fn peak_audit_inc "const unsigned int field"
.Ft const char *
.Fn peak_audit_name "const unsigned int field"
.Ft void
.Fn peak_audit_set "const unsigned int field" "const uint64_t value"
.Ft void
.Fn peak_audit_sync "struct peak_audit *export"
.Sh DESCREPTION
The
.Nm peak_audit
API functions provide a thread-safe way to keep counters and
similar sorts of statistics for individual subsystems.
The API is ready for use without explicit initialisation.
The private memory location per thread is never leaked to the
outside, so that there is no need for locking access.
Care should be taken when threads are destroyed as their
.Nm peak_audit
state will be destroyed as well.
It may be disabled by defining
.Dv WITHOUT_AUDIT
prior to including
.In peak.h .
.Pp
The functions
.Fn peak_audit_add ,
.Fn peak_audit_inc
and
.Fn peak_audit_set
may be used to manipulate a given
.Va field .
.Pp
The function
.Fn peak_audit_get
returns the current value of
.Va field ,
in case a surgical need to operate on the value arises.
.Pp
The function
.Fn peak_audit_sync
is used to export the thread's audit data to a public location.
It will also clear all internal fields for consistency.
.Pp
The function
.Fn peak_audit_name
returns a human-readable name of a given
.Va field .
.Sh AUTHORS
.An Franco Fichtner Aq Mt franco@packetwerk.com
