/*
 * Copyright (c) 2014 Tobias Boertitz <tobias@packetwerk.com>
 * Copyright (c) 2014 Franco Fichtner <franco@packetwerk.com>
 *
 * Permission to use, copy, modify, and distribute this software for any
 * purpose with or without fee is hereby granted, provided that the above
 * copyright notice and this permission notice appear in all copies.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 * WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
 * ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
 * ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
 * OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 */

#include <peak.h>
#include <magic.h>

/*
 * Begin of autogenerated section.  DO NOT EDIT.
 */

static const struct magic_item magic_items[] = {
	{ MAGIC_UNKNOWN, "unknown", "" },	/* `unknown' placeholder */
	{ MAGIC_DICOM_MEDICAL_IMAGING_DATA, "DICOM medical imaging data", "application/dicom" },
	{ MAGIC_NODE_JS_SCRIPT_TEXT_EXECUTABLE, "Node.js script text executable", "application/javascript" },
	{ MAGIC_BINHEX_BINARY_TEXT, "BinHex binary text", "application/mac-binhex40" },
	{ MAGIC_MARC21, "MARC21", "application/marc" },
	{ MAGIC_MICROSOFT_WORD_DOCUMENT, "Microsoft Word Document", "application/msword" },
	{ MAGIC_PACKED_DATA, "packed data", "application/octet-stream" },
	{ MAGIC_OGG_DATA, "Ogg data", "application/ogg" },
	{ MAGIC_PDF_DOCUMENT, "PDF document", "application/pdf" },
	{ MAGIC_PGP_MESSAGE, "PGP message", "application/pgp" },
	{ MAGIC_PGP_PUBLIC_KEY_BLOCK, "PGP public key block", "application/pgp-keys" },
	{ MAGIC_PGP_SIGNATURE, "PGP signature", "application/pgp-signature" },
	{ MAGIC_POSTSCRIPT_DOCUMENT_TEXT, "PostScript document text", "application/postscript" },
	{ MAGIC_SEREAL_DATA, "Sereal data", "application/sereal" },
	{ MAGIC_PART_OF_MULTIPART_DEBIAN_PACKAGE, "part of multipart Debian package", "application/vnd.debian.binary-package" },
	{ MAGIC_FDF_DOCUMENT, "FDF document", "application/vnd.fdf" },
	{ MAGIC_SPLINE_FONT_DATABASE, "Spline Font Database", "application/vnd.font-fontforge-sfd" },
	{ MAGIC_GOOGLE_KML_DOCUMENT, "Google KML document", "application/vnd.google-earth.kml+xml" },
	{ MAGIC_COMPRESSED_GOOGLE_KML_DOCUMENT__INCLUDING_RESOURCES_, "Compressed Google KML Document, including resources.", "application/vnd.google-earth.kmz" },
	{ MAGIC_SUN_KCMS_ICC_PROFILE, "Sun KCMS ICC Profile", "application/vnd.iccprofile" },
	{ MAGIC_LOTUS_WORDPRO, "Lotus WordPro", "application/vnd.lotus-wordpro" },
	{ MAGIC_MICROSOFT_CABINET_ARCHIVE_DATA, "Microsoft Cabinet archive data", "application/vnd.ms-cab-compressed" },
	{ MAGIC_MICROSOFT_EXCEL_WORKSHEET, "Microsoft Excel Worksheet", "application/vnd.ms-excel" },
	{ MAGIC_EMBEDDED_OPENTYPE__EOT_, "Embedded OpenType (EOT)", "application/vnd.ms-fontobject" },
	{ MAGIC_OPENTYPE_FONT_DATA, "OpenType font data", "application/vnd.ms-opentype" },
	{ MAGIC_TRANSPORT_NEUTRAL_ENCAPSULATION_FORMAT, "Transport Neutral Encapsulation Format", "application/vnd.ms-tnef" },
	{ MAGIC_MICROSOFT_WORD_2007P, "Microsoft Word 2007+", "application/vnd.openxmlformats-officedocument.wordprocessingml.document" },
	{ MAGIC_REALMEDIA_FILE, "RealMedia file", "application/vnd.rn-realmedia" },
	{ MAGIC_SYMBIAN_INSTALLATION_FILE, "Symbian installation file", "application/vnd.symbian.install" },
	{ MAGIC_TCPDUMP_CAPTURE_FILE, "tcpdump capture file", "application/vnd.tcpdump.pcap" },
	{ MAGIC_LOTUS_1_2_3, "Lotus 1-2-3", "application/x-123" },
	{ MAGIC_ABOOK_ADDRESS_BOOK, "abook address book", "application/x-abook-addressbook" },
	{ MAGIC_ARC_ARCHIVE_DATA, "ARC archive data", "application/x-arc" },
	{ MAGIC_MIPS_ARCHIVE, "MIPS archive", "application/x-archive" },
	{ MAGIC_ARJ_ARCHIVE_DATA, "ARJ archive data", "application/x-arj" },
	{ MAGIC_BITTORRENT_FILE, "BitTorrent file", "application/x-bittorrent" },
	{ MAGIC_BZIP2_COMPRESSED_DATA, "bzip2 compressed data", "application/x-bzip2" },
	{ MAGIC_COMPRESS_D_DATA, "compress'd data", "application/x-compress" },
	{ MAGIC_BYTE_SWAPPED_CPIO_ARCHIVE, "byte-swapped cpio archive", "application/x-cpio" },
	{ MAGIC_BERKELEY_DB, "Berkeley DB", "application/x-dbm" },
	{ MAGIC_WINDOWS_PROGRAM_INFORMATION_FILE, "Windows Program Information File", "application/x-dosexec" },
	{ MAGIC_TEX_DVI_FILE, "TeX DVI file", "application/x-dvi" },
	{ MAGIC_EET_ARCHIVE, "EET archive", "application/x-eet" },
	{ MAGIC_EMACS__BYTE_COMPILED_LISP_DATA, "Emacs  byte-compiled Lisp data", "application/x-elc" },
	{ MAGIC_X11_SNF_FONT_DATA__LSB_FIRST, "X11 SNF font data, LSB first", "application/x-font-sfn" },
	{ MAGIC_TRUETYPE_FONT_DATA, "TrueType font data", "application/x-font-ttf" },
	{ MAGIC_FREEMIND_DOCUMENT, "Freemind document", "application/x-freemind" },
	{ MAGIC_FREEPLANE_DOCUMENT, "Freeplane document", "application/x-freeplane" },
	{ MAGIC_GNU_DBM_OR_NDBM_DATABASE, "GNU dbm or ndbm database", "application/x-gdbm" },
	{ MAGIC_GNUMERIC_SPREADSHEET, "Gnumeric spreadsheet", "application/x-gnumeric" },
	{ MAGIC_GPG_KEY_PUBLIC_RING, "GPG key public ring", "application/x-gnupg-keyring" },
	{ MAGIC_GZIP_COMPRESSED_DATA, "gzip compressed data", "application/x-gzip" },
	{ MAGIC_HIERARCHICAL_DATA_FORMAT_DATA, "Hierarchical Data Format data", "application/x-hdf" },
	{ MAGIC_HANGUL__KOREAN__WORD_PROCESSOR_FILE_2000, "Hangul (Korean) Word Processor File 2000", "application/x-hwp" },
	{ MAGIC_INTERNET_ARCHIVE_FILE, "Internet Archive File", "application/x-ia-arc" },
	{ MAGIC_JUST_SYSTEM_WORD_PROCESSOR_ICHITARO, "Just System Word Processor Ichitaro", "application/x-ichitaro4" },
	{ MAGIC_JUST_SYSTEM_WORD_PROCESSOR_ICHITARO_V5, "Just System Word Processor Ichitaro v5", "application/x-ichitaro5" },
	{ MAGIC_JUST_SYSTEM_WORD_PROCESSOR_ICHITARO_V6, "Just System Word Processor Ichitaro v6", "application/x-ichitaro6" },
	{ MAGIC_ISO_9660_CD_ROM_FILESYSTEM_DATA__RAW_2352_BYTE_SECTORS_, "ISO 9660 CD-ROM filesystem data (raw 2352 byte sectors)", "application/x-iso9660-image" },
	{ MAGIC_JAVA_APPLET, "Java Applet", "application/x-java-applet" },
	{ MAGIC_JAVA_JCE_KEYSTORE, "Java JCE KeyStore", "application/x-java-jce-keystore" },
	{ MAGIC_JAVA_KEYSTORE, "Java KeyStore", "application/x-java-keystore" },
	{ MAGIC_KDE_FILE, "KDE file", "application/x-kdelnk" },
	{ MAGIC_LHA_ARCHIVE_DATA, "LHa archive data", "application/x-lha" },
	{ MAGIC_LHARC_1_X_ARX_ARCHIVE_DATA__LH0_, "LHarc 1.x/ARX archive data [lh0]", "application/x-lharc" },
	{ MAGIC_LZ4_COMPRESSED_DATA__V0_1_V0_9_, "LZ4 compressed data (v0.1-v0.9)", "application/x-lz4" },
	{ MAGIC_LZIP_COMPRESSED_DATA, "lzip compressed data", "application/x-lzip" },
	{ MAGIC_LZMA_COMPRESSED_DATA_, "LZMA compressed data,", "application/x-lzma" },
	{ MAGIC_FRAMEMAKER_FILE, "FrameMaker file", "application/x-mif" },
	{ MAGIC_MICROSOFT_ACCESS_DATABASE, "Microsoft Access Database", "application/x-msaccess" },
	{ MAGIC_PGP_KEY_RING, "PGP key ring", "application/x-pgp-keyring" },
	{ MAGIC_WINDOWS_PRECOMPILED_INF, "Windows Precompiled iNF", "application/x-pnf" },
	{ MAGIC_MOTOROLA_QUARK_EXPRESS_DOCUMENT__ENGLISH_, "Motorola Quark Express Document (English)", "application/x-quark-xpress-3" },
	{ MAGIC_APPLE_QUICKTIME_COMPRESSED_ARCHIVE, "Apple QuickTime compressed archive", "application/x-quicktime-player" },
	{ MAGIC_RAR_ARCHIVE_DATA_, "RAR archive data,", "application/x-rar" },
	{ MAGIC_RPM, "RPM", "application/x-rpm" },
	{ MAGIC_SC_SPREADSHEET_FILE, "sc spreadsheet file", "application/x-sc" },
	{ MAGIC_SCRIBUS_DOCUMENT, "Scribus Document", "application/x-scribus" },
	{ MAGIC_SNAPPY_FRAMED_DATA, "snappy framed data", "application/x-snappy-framed" },
	{ MAGIC_STUFFIT_ARCHIVE, "StuffIt Archive", "application/x-stuffit" },
	{ MAGIC_PKG_DATASTREAM__SVR4_, "pkg Datastream (SVR4)", "application/x-svr4-package" },
	{ MAGIC_GNU_TAR_ARCHIVE, "GNU tar archive", "application/x-tar" },
	{ MAGIC_TEX_FONT_METRIC_DATA, "TeX font metric data", "application/x-tex-tfm" },
	{ MAGIC_INITIALIZATION_CONFIGURATION, "INItialization configuration", "application/x-wine-extension-ini" },
	{ MAGIC_XZ_COMPRESSED_DATA, "XZ compressed data", "application/x-xz" },
	{ MAGIC_ZOO_ARCHIVE_DATA, "Zoo archive data", "application/x-zoo" },
	{ MAGIC_XML_DOCUMENT_TEXT, "XML document text", "application/xml" },
	{ MAGIC_XML_SITEMAP_DOCUMENT_TEXT, "XML Sitemap document text", "application/xml-sitemap" },
	{ MAGIC_ZIP_MULTI_VOLUME_ARCHIVE_DATA__AT_LEAST_PKZIP_V2_50_TO_EXTRACT, "Zip multi-volume archive data, at least PKZIP v2.50 to extract", "application/zip" },
	{ MAGIC_STANDARD_MIDI_DATA, "Standard MIDI data", "audio/midi" },
	{ MAGIC_MPEG_ADTS, "MPEG ADTS", "audio/mpeg" },
	{ MAGIC_ATSC_A_52_AKA_AC_3_AKA_DOLBY_DIGITAL_STREAM_, "ATSC A/52 aka AC-3 aka Dolby Digital stream,", "audio/vnd.dolby.dd-raw" },
	{ MAGIC_MONKEY_S_AUDIO_COMPRESSED_FORMAT, "Monkey's Audio compressed format", "audio/x-ape" },
	{ MAGIC_FLAC_AUDIO_BITSTREAM_DATA, "FLAC audio bitstream data", "audio/x-flac" },
	{ MAGIC_MPEG_ADIF__AAC, "MPEG ADIF, AAC", "audio/x-hx-aac-adif" },
	{ MAGIC_MPEG_ADTS__AAC, "MPEG ADTS, AAC", "audio/x-hx-aac-adts" },
	{ MAGIC_MODULE_SOUND_DATA, "module sound data", "audio/x-mod" },
	{ MAGIC_MPEG_4_LOAS, "MPEG-4 LOAS", "audio/x-mp4a-latm" },
	{ MAGIC_MUSEPACK_AUDIO, "Musepack audio", "audio/x-musepack" },
	{ MAGIC_REALAUDIO_SOUND_FILE, "RealAudio sound file", "audio/x-pn-realaudio" },
	{ MAGIC_UNKNOWN_AUDIO_FORMAT, "Unknown audio format", "audio/x-unknown" },
	{ MAGIC_MBWF_RF64_AUDIO, "MBWF/RF64 audio", "audio/x-wav" },
	{ MAGIC_PROTEIN_DATA_BANK_DATA__ID_CODE__S, "Protein Data Bank data, ID Code s", "chemical/x-pdb" },
	{ MAGIC_GIF_IMAGE_DATA, "GIF image data", "image/gif" },
	{ MAGIC_JPEG_2000_IMAGE, "JPEG 2000 image", "image/jp2" },
	{ MAGIC_JPEG_IMAGE_DATA, "JPEG image data", "image/jpeg" },
	{ MAGIC_PNG_IMAGE_DATA, "PNG image data", "image/png" },
	{ MAGIC_SVG_SCALABLE_VECTOR_GRAPHICS_IMAGE, "SVG Scalable Vector Graphics image", "image/svg+xml" },
	{ MAGIC_TIFF_IMAGE_DATA, "TIFF image data", "image/tiff" },
	{ MAGIC_ADOBE_PHOTOSHOP_IMAGE, "Adobe Photoshop Image", "image/vnd.adobe.photoshop" },
	{ MAGIC_DJVU_MULTIPLE_PAGE_DOCUMENT, "DjVu multiple page document", "image/vnd.djvu" },
	{ MAGIC_DWG_AUTODESK_AUTOCAD_RELEASE_1_40, "DWG AutoDesk AutoCAD Release 1.40", "image/vnd.dwg" },
	{ MAGIC_AWARD_BIOS_LOGO__136_X_126, "Award BIOS Logo, 136 x 126", "image/x-award-bioslogo" },
	{ MAGIC_AWARD_BIOS_BITMAP, "Award BIOS bitmap", "image/x-award-bmp" },
	{ MAGIC_CANON_CR2_RAW_IMAGE_DATA, "Canon CR2 raw image data", "image/x-canon-cr2" },
	{ MAGIC_CANON_CIFF_RAW_IMAGE_DATA, "Canon CIFF raw image data", "image/x-canon-crw" },
	{ MAGIC_CARTESIAN_PERCEPTUAL_COMPRESSION_IMAGE, "Cartesian Perceptual Compression image", "image/x-cpi" },
	{ MAGIC_MS_WINDOWS_CURSOR_RESOURCE, "MS Windows cursor resource", "image/x-cur" },
	{ MAGIC_DPX_IMAGE_DATA__BIG_ENDIAN_, "DPX image data, big-endian,", "image/x-dpx" },
	{ MAGIC_OPENEXR_IMAGE_DATA_, "OpenEXR image data,", "image/x-exr" },
	{ MAGIC_MS_WINDOWS_ICON_RESOURCE, "MS Windows icon resource", "image/x-icon" },
	{ MAGIC_SYSLINUX__LSS16_IMAGE_DATA, "SYSLINUX' LSS16 image data", "image/x-lss16" },
	{ MAGIC_PC_BITMAP__OS_2_1_X_FORMAT, "PC bitmap, OS/2 1.x format", "image/x-ms-bmp" },
	{ MAGIC_NIFF_IMAGE_DATA, "NIFF image data", "image/x-niff" },
	{ MAGIC_OLYMPUS_ORF_RAW_IMAGE_DATA__BIG_ENDIAN, "Olympus ORF raw image data, big-endian", "image/x-olympus-orf" },
	{ MAGIC_PAINT_NET_IMAGE_DATA, "Paint.NET image data", "image/x-paintnet" },
	{ MAGIC_PCX, "PCX", "image/x-pcx" },
	{ MAGIC_PROGRESSIVE_GRAPHICS_IMAGE_DATA_, "Progressive Graphics image data,", "image/x-pgf" },
	{ MAGIC_POLAR_MONITOR_BITMAP_TEXT, "Polar Monitor Bitmap text", "image/x-polar-monitor-bitmap" },
	{ MAGIC_NETPBM_PPM_IMAGE_FILE, "Netpbm PPM image file", "image/x-portable-pixmap" },
	{ MAGIC_APPLE_QUICKTIME_IMAGE__FAST_START_, "Apple QuickTime image (fast start)", "image/x-quicktime" },
	{ MAGIC_UNKNOWN_IMAGE_FORMAT, "Unknown image format", "image/x-unknown" },
	{ MAGIC_FOVEON_X3F_RAW_IMAGE_DATA, "Foveon X3F raw image data", "image/x-x3f" },
	{ MAGIC_GIMP_XCF_IMAGE_DATA_, "GIMP XCF image data,", "image/x-xcf" },
	{ MAGIC_XCURSOR_DATA, "Xcursor data", "image/x-xcursor" },
	{ MAGIC_X_PIXMAP_IMAGE_TEXT, "X pixmap image text", "image/x-xpmi" },
	{ MAGIC_XWD_X_WINDOW_DUMP_IMAGE_DATA, "XWD X Window Dump image data", "image/x-xwindowdump" },
	{ MAGIC_NEWS_TEXT, "news text", "message/news" },
	{ MAGIC_MAIL_TEXT, "mail text", "message/rfc822" },
	{ MAGIC_VRML_FILE, "VRML file", "model/vrml" },
	{ MAGIC_X3D__EXTENSIBLE_3D__MODEL_XML_TEXT, "X3D (Extensible 3D) model xml text", "model/x3d" },
	{ MAGIC_VCALENDAR_CALENDAR_FILE, "vCalendar calendar file", "text/calendar" },
	{ MAGIC_HTML_DOCUMENT_TEXT, "HTML document text", "text/html" },
	{ MAGIC_PGP_ENCRYPTED_DATA, "PGP encrypted data", "text/PGP" },
	{ MAGIC_RICH_TEXT_FORMAT_DATA_, "Rich Text Format data,", "text/rtf" },
	{ MAGIC_TEXMACS_DOCUMENT_TEXT, "TeXmacs document text", "text/texmacs" },
	{ MAGIC_TROFF_OR_PREPROCESSOR_INPUT_TEXT, "troff or preprocessor input text", "text/troff" },
	{ MAGIC_ASSEMBLER_SOURCE_TEXT, "assembler source text", "text/x-asm" },
	{ MAGIC_AWK_SCRIPT_TEXT_EXECUTABLE, "awk script text executable", "text/x-awk" },
	{ MAGIC_BCPL_SOURCE_TEXT, "BCPL source text", "text/x-bcpl" },
	{ MAGIC_C_SOURCE_TEXT, "C source text", "text/x-c" },
	{ MAGIC_CPP_SOURCE_TEXT, "C++ source text", "text/x-c++" },
	{ MAGIC_UNIFIED_DIFF_OUTPUT_TEXT, "unified diff output text", "text/x-diff" },
	{ MAGIC_FORTRAN_PROGRAM, "FORTRAN program", "text/x-fortran" },
	{ MAGIC_GNU_AWK_SCRIPT_TEXT_EXECUTABLE, "GNU awk script text executable", "text/x-gawk" },
	{ MAGIC_GNU_INFO_TEXT, "GNU Info text", "text/x-info" },
	{ MAGIC_JAVA_SOURCE, "Java source", "text/x-java" },
	{ MAGIC_LISP_SCHEME_PROGRAM_TEXT, "Lisp/Scheme program text", "text/x-lisp" },
	{ MAGIC_LUA_SCRIPT_TEXT_EXECUTABLE, "Lua script text executable", "text/x-lua" },
	{ MAGIC_M4_MACRO_PROCESSOR_SCRIPT_TEXT, "M4 macro processor script text", "text/x-m4" },
	{ MAGIC_MAKEFILE_SCRIPT_TEXT, "makefile script text", "text/x-makefile" },
	{ MAGIC_DOS_BATCH_FILE_TEXT, "DOS batch file text", "text/x-msdos-batch" },
	{ MAGIC_NEW_AWK_SCRIPT_TEXT_EXECUTABLE, "new awk script text executable", "text/x-nawk" },
	{ MAGIC_PASCAL_SOURCE_TEXT, "Pascal source text", "text/x-pascal" },
	{ MAGIC_PERL_SCRIPT_TEXT, "Perl script text", "text/x-perl" },
	{ MAGIC_PHP_SCRIPT_TEXT, "PHP script text", "text/x-php" },
	{ MAGIC_GNU_GETTEXT_MESSAGE_CATALOGUE_TEXT, "GNU gettext message catalogue text", "text/x-po" },
	{ MAGIC_PYTHON_SCRIPT_TEXT_EXECUTABLE, "Python script text executable", "text/x-python" },
	{ MAGIC_RUBY_SOURCE_TEXT, "Ruby source text", "text/x-ruby" },
	{ MAGIC_SHELLSCRIPT_TEXT_EXECUTABLE, "Shellscript text executable", "text/x-shellscript" },
	{ MAGIC_TCL_TK_SCRIPT_TEXT_EXECUTABLE, "Tcl/Tk script text executable", "text/x-tcl" },
	{ MAGIC_LATEX_FILE, "LaTeX file", "text/x-tex" },
	{ MAGIC_TEXINFO_SOURCE_TEXT, "Texinfo source text", "text/x-texinfo" },
	{ MAGIC_VCARD_VISITING_CARD, "vCard visiting card", "text/x-vcard" },
	{ MAGIC_XMCD_DATABASE_FILE_FOR_KSCD, "xmcd database file for kscd", "text/x-xmcd" },
	{ MAGIC_MPEG_SEQUENCE, "MPEG sequence", "video/mpeg" },
	{ MAGIC_APPLE_QUICKTIME_MOVIE, "Apple QuickTime movie", "video/quicktime" },
	{ MAGIC_WEBM, "WebM", "video/webm" },
	{ MAGIC_FLC_ANIMATION, "FLC animation", "video/x-flc" },
	{ MAGIC_FLI_ANIMATION__320X200X8, "FLI animation, 320x200x8", "video/x-fli" },
	{ MAGIC_MACROMEDIA_FLASH_VIDEO, "Macromedia Flash Video", "video/x-flv" },
	{ MAGIC_JNG_VIDEO_DATA_, "JNG video data,", "video/x-jng" },
	{ MAGIC_MNG_VIDEO_DATA_, "MNG video data,", "video/x-mng" },
	{ MAGIC_MICROSOFT_ASF, "Microsoft ASF", "video/x-ms-asf" },
	{ MAGIC_SILICON_GRAPHICS_MOVIE_FILE, "Silicon Graphics movie file", "video/x-sgi-movie" },
	{ MAGIC_SYMBIAN_INSTALLATION_FILE__SYMBIAN_OS_9_X_, "Symbian installation file (Symbian OS 9.x)", "x-epoc/x-sisx-app" },
};

/*
 * End of autogenerated section.
 */

struct peak_magic {
	magic_t handle;
};

unsigned int
peak_magic_get(struct peak_magic *self, const char *buf, const size_t len)
{
	const char *name;

	name = magic_buffer(self->handle, buf, len);
	if (!name) {
		error("error retrieving mime type: %s\n",
		    magic_error(self->handle));
		return (MAGIC_PACKED_DATA);
	}

	return (peak_magic_number(name));
}

void
peak_magic_exit(struct peak_magic *self)
{
	if (!self) {
		return;
	}

	magic_close(self->handle);
	free(self);
}

struct peak_magic *
peak_magic_init(void)
{
	struct peak_magic *self;

	self = calloc(1, sizeof(*self));
	if (!self) {
		return (NULL);
	}

	self->handle = magic_open(MAGIC_MIME_TYPE);
	if (!self->handle) {
		free(self);
		return (NULL);
	}

	if (magic_load(self->handle, NULL)) {
		peak_magic_exit(self);
		return (NULL);
	}

	return (self);
}

static int
kw_cmp(const void *x, const void *yy)
{
        const struct magic_item *y = yy;

        return (strcasecmp(x, y->mime_type));
}

unsigned int
peak_magic_number(const char *name)
{
	struct magic_item *mime;

	mime = bsearch(name, magic_items, lengthof(magic_items),
	    sizeof(magic_items[0]), kw_cmp);
	if (!mime) {
		return (MAGIC_PACKED_DATA);
	}

	return (mime->guid);
}


const char *
peak_magic_name(const unsigned int number)
{
	if (number >= MAGIC_MAX) {
		return (NULL);
	}

	return (magic_items[number].mime_type);
}

const char *
peak_magic_desc(const unsigned int number)
{
	if (number >= MAGIC_MAX) {
		return (NULL);
	}

	return (magic_items[number].description);
}
