/*
 * Copyright (c) 2012-2014 Franco Fichtner <franco@packetwerk.com>
 *
 * Permission to use, copy, modify, and distribute this software for any
 * purpose with or without fee is hereby granted, provided that the above
 * copyright notice and this permission notice appear in all copies.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 * WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
 * ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
 * ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
 * OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 */

#include <fcntl.h>
#include <peak.h>
#include <unistd.h>

#define LOCATE_DEFAULT	"/usr/local/var/peak/locate.bin"

/*
 * Begin of autogenerated section.  DO NOT EDIT.
 */

static const struct locate_item locate_items[] = {
	{ LOCATE_UNKNOWN, "", "unknown" },	/* `unknown' placeholder */
	{ LOCATE_AD, "AD", "Andorra" },
	{ LOCATE_AE, "AE", "United Arab Emirates" },
	{ LOCATE_AF, "AF", "Afghanistan" },
	{ LOCATE_AG, "AG", "Antigua & Barbuda" },
	{ LOCATE_AI, "AI", "Anguilla" },
	{ LOCATE_AL, "AL", "Albania" },
	{ LOCATE_AM, "AM", "Armenia" },
	{ LOCATE_AO, "AO", "Angola" },
	{ LOCATE_AQ, "AQ", "Antarctica" },
	{ LOCATE_AR, "AR", "Argentina" },
	{ LOCATE_AS, "AS", "Samoa (American)" },
	{ LOCATE_AT, "AT", "Austria" },
	{ LOCATE_AU, "AU", "Australia" },
	{ LOCATE_AW, "AW", "Aruba" },
	{ LOCATE_AX, "AX", "Aaland Islands" },
	{ LOCATE_AZ, "AZ", "Azerbaijan" },
	{ LOCATE_BA, "BA", "Bosnia & Herzegovina" },
	{ LOCATE_BB, "BB", "Barbados" },
	{ LOCATE_BD, "BD", "Bangladesh" },
	{ LOCATE_BE, "BE", "Belgium" },
	{ LOCATE_BF, "BF", "Burkina Faso" },
	{ LOCATE_BG, "BG", "Bulgaria" },
	{ LOCATE_BH, "BH", "Bahrain" },
	{ LOCATE_BI, "BI", "Burundi" },
	{ LOCATE_BJ, "BJ", "Benin" },
	{ LOCATE_BL, "BL", "St Barthelemy" },
	{ LOCATE_BM, "BM", "Bermuda" },
	{ LOCATE_BN, "BN", "Brunei" },
	{ LOCATE_BO, "BO", "Bolivia" },
	{ LOCATE_BQ, "BQ", "Caribbean Netherlands" },
	{ LOCATE_BR, "BR", "Brazil" },
	{ LOCATE_BS, "BS", "Bahamas" },
	{ LOCATE_BT, "BT", "Bhutan" },
	{ LOCATE_BV, "BV", "Bouvet Island" },
	{ LOCATE_BW, "BW", "Botswana" },
	{ LOCATE_BY, "BY", "Belarus" },
	{ LOCATE_BZ, "BZ", "Belize" },
	{ LOCATE_CA, "CA", "Canada" },
	{ LOCATE_CC, "CC", "Cocos (Keeling) Islands" },
	{ LOCATE_CD, "CD", "Congo (Dem. Rep.)" },
	{ LOCATE_CF, "CF", "Central African Rep." },
	{ LOCATE_CG, "CG", "Congo (Rep.)" },
	{ LOCATE_CH, "CH", "Switzerland" },
	{ LOCATE_CI, "CI", "Cote d'Ivoire" },
	{ LOCATE_CK, "CK", "Cook Islands" },
	{ LOCATE_CL, "CL", "Chile" },
	{ LOCATE_CM, "CM", "Cameroon" },
	{ LOCATE_CN, "CN", "China" },
	{ LOCATE_CO, "CO", "Colombia" },
	{ LOCATE_CR, "CR", "Costa Rica" },
	{ LOCATE_CU, "CU", "Cuba" },
	{ LOCATE_CV, "CV", "Cape Verde" },
	{ LOCATE_CW, "CW", "Curacao" },
	{ LOCATE_CX, "CX", "Christmas Island" },
	{ LOCATE_CY, "CY", "Cyprus" },
	{ LOCATE_CZ, "CZ", "Czech Republic" },
	{ LOCATE_DE, "DE", "Germany" },
	{ LOCATE_DJ, "DJ", "Djibouti" },
	{ LOCATE_DK, "DK", "Denmark" },
	{ LOCATE_DM, "DM", "Dominica" },
	{ LOCATE_DO, "DO", "Dominican Republic" },
	{ LOCATE_DZ, "DZ", "Algeria" },
	{ LOCATE_EC, "EC", "Ecuador" },
	{ LOCATE_EE, "EE", "Estonia" },
	{ LOCATE_EG, "EG", "Egypt" },
	{ LOCATE_EH, "EH", "Western Sahara" },
	{ LOCATE_ER, "ER", "Eritrea" },
	{ LOCATE_ES, "ES", "Spain" },
	{ LOCATE_ET, "ET", "Ethiopia" },
	{ LOCATE_FI, "FI", "Finland" },
	{ LOCATE_FJ, "FJ", "Fiji" },
	{ LOCATE_FK, "FK", "Falkland Islands" },
	{ LOCATE_FM, "FM", "Micronesia" },
	{ LOCATE_FO, "FO", "Faroe Islands" },
	{ LOCATE_FR, "FR", "France" },
	{ LOCATE_GA, "GA", "Gabon" },
	{ LOCATE_GB, "GB", "Britain (UK)" },
	{ LOCATE_GD, "GD", "Grenada" },
	{ LOCATE_GE, "GE", "Georgia" },
	{ LOCATE_GF, "GF", "French Guiana" },
	{ LOCATE_GG, "GG", "Guernsey" },
	{ LOCATE_GH, "GH", "Ghana" },
	{ LOCATE_GI, "GI", "Gibraltar" },
	{ LOCATE_GL, "GL", "Greenland" },
	{ LOCATE_GM, "GM", "Gambia" },
	{ LOCATE_GN, "GN", "Guinea" },
	{ LOCATE_GP, "GP", "Guadeloupe" },
	{ LOCATE_GQ, "GQ", "Equatorial Guinea" },
	{ LOCATE_GR, "GR", "Greece" },
	{ LOCATE_GS, "GS", "South Georgia & the South Sandwich Islands" },
	{ LOCATE_GT, "GT", "Guatemala" },
	{ LOCATE_GU, "GU", "Guam" },
	{ LOCATE_GW, "GW", "Guinea-Bissau" },
	{ LOCATE_GY, "GY", "Guyana" },
	{ LOCATE_HK, "HK", "Hong Kong" },
	{ LOCATE_HM, "HM", "Heard Island & McDonald Islands" },
	{ LOCATE_HN, "HN", "Honduras" },
	{ LOCATE_HR, "HR", "Croatia" },
	{ LOCATE_HT, "HT", "Haiti" },
	{ LOCATE_HU, "HU", "Hungary" },
	{ LOCATE_ID, "ID", "Indonesia" },
	{ LOCATE_IE, "IE", "Ireland" },
	{ LOCATE_IL, "IL", "Israel" },
	{ LOCATE_IM, "IM", "Isle of Man" },
	{ LOCATE_IN, "IN", "India" },
	{ LOCATE_IO, "IO", "British Indian Ocean Territory" },
	{ LOCATE_IQ, "IQ", "Iraq" },
	{ LOCATE_IR, "IR", "Iran" },
	{ LOCATE_IS, "IS", "Iceland" },
	{ LOCATE_IT, "IT", "Italy" },
	{ LOCATE_JE, "JE", "Jersey" },
	{ LOCATE_JM, "JM", "Jamaica" },
	{ LOCATE_JO, "JO", "Jordan" },
	{ LOCATE_JP, "JP", "Japan" },
	{ LOCATE_KE, "KE", "Kenya" },
	{ LOCATE_KG, "KG", "Kyrgyzstan" },
	{ LOCATE_KH, "KH", "Cambodia" },
	{ LOCATE_KI, "KI", "Kiribati" },
	{ LOCATE_KM, "KM", "Comoros" },
	{ LOCATE_KN, "KN", "St Kitts & Nevis" },
	{ LOCATE_KP, "KP", "Korea (North)" },
	{ LOCATE_KR, "KR", "Korea (South)" },
	{ LOCATE_KW, "KW", "Kuwait" },
	{ LOCATE_KY, "KY", "Cayman Islands" },
	{ LOCATE_KZ, "KZ", "Kazakhstan" },
	{ LOCATE_LA, "LA", "Laos" },
	{ LOCATE_LB, "LB", "Lebanon" },
	{ LOCATE_LC, "LC", "St Lucia" },
	{ LOCATE_LI, "LI", "Liechtenstein" },
	{ LOCATE_LK, "LK", "Sri Lanka" },
	{ LOCATE_LR, "LR", "Liberia" },
	{ LOCATE_LS, "LS", "Lesotho" },
	{ LOCATE_LT, "LT", "Lithuania" },
	{ LOCATE_LU, "LU", "Luxembourg" },
	{ LOCATE_LV, "LV", "Latvia" },
	{ LOCATE_LY, "LY", "Libya" },
	{ LOCATE_MA, "MA", "Morocco" },
	{ LOCATE_MC, "MC", "Monaco" },
	{ LOCATE_MD, "MD", "Moldova" },
	{ LOCATE_ME, "ME", "Montenegro" },
	{ LOCATE_MF, "MF", "St Martin (French part)" },
	{ LOCATE_MG, "MG", "Madagascar" },
	{ LOCATE_MH, "MH", "Marshall Islands" },
	{ LOCATE_MK, "MK", "Macedonia" },
	{ LOCATE_ML, "ML", "Mali" },
	{ LOCATE_MM, "MM", "Myanmar (Burma)" },
	{ LOCATE_MN, "MN", "Mongolia" },
	{ LOCATE_MO, "MO", "Macau" },
	{ LOCATE_MP, "MP", "Northern Mariana Islands" },
	{ LOCATE_MQ, "MQ", "Martinique" },
	{ LOCATE_MR, "MR", "Mauritania" },
	{ LOCATE_MS, "MS", "Montserrat" },
	{ LOCATE_MT, "MT", "Malta" },
	{ LOCATE_MU, "MU", "Mauritius" },
	{ LOCATE_MV, "MV", "Maldives" },
	{ LOCATE_MW, "MW", "Malawi" },
	{ LOCATE_MX, "MX", "Mexico" },
	{ LOCATE_MY, "MY", "Malaysia" },
	{ LOCATE_MZ, "MZ", "Mozambique" },
	{ LOCATE_NA, "NA", "Namibia" },
	{ LOCATE_NC, "NC", "New Caledonia" },
	{ LOCATE_NE, "NE", "Niger" },
	{ LOCATE_NF, "NF", "Norfolk Island" },
	{ LOCATE_NG, "NG", "Nigeria" },
	{ LOCATE_NI, "NI", "Nicaragua" },
	{ LOCATE_NL, "NL", "Netherlands" },
	{ LOCATE_NO, "NO", "Norway" },
	{ LOCATE_NP, "NP", "Nepal" },
	{ LOCATE_NR, "NR", "Nauru" },
	{ LOCATE_NU, "NU", "Niue" },
	{ LOCATE_NZ, "NZ", "New Zealand" },
	{ LOCATE_OM, "OM", "Oman" },
	{ LOCATE_PA, "PA", "Panama" },
	{ LOCATE_PE, "PE", "Peru" },
	{ LOCATE_PF, "PF", "French Polynesia" },
	{ LOCATE_PG, "PG", "Papua New Guinea" },
	{ LOCATE_PH, "PH", "Philippines" },
	{ LOCATE_PK, "PK", "Pakistan" },
	{ LOCATE_PL, "PL", "Poland" },
	{ LOCATE_PM, "PM", "St Pierre & Miquelon" },
	{ LOCATE_PN, "PN", "Pitcairn" },
	{ LOCATE_PR, "PR", "Puerto Rico" },
	{ LOCATE_PS, "PS", "Palestine" },
	{ LOCATE_PT, "PT", "Portugal" },
	{ LOCATE_PW, "PW", "Palau" },
	{ LOCATE_PY, "PY", "Paraguay" },
	{ LOCATE_QA, "QA", "Qatar" },
	{ LOCATE_RE, "RE", "Reunion" },
	{ LOCATE_RO, "RO", "Romania" },
	{ LOCATE_RS, "RS", "Serbia" },
	{ LOCATE_RU, "RU", "Russia" },
	{ LOCATE_RW, "RW", "Rwanda" },
	{ LOCATE_SA, "SA", "Saudi Arabia" },
	{ LOCATE_SB, "SB", "Solomon Islands" },
	{ LOCATE_SC, "SC", "Seychelles" },
	{ LOCATE_SD, "SD", "Sudan" },
	{ LOCATE_SE, "SE", "Sweden" },
	{ LOCATE_SG, "SG", "Singapore" },
	{ LOCATE_SH, "SH", "St Helena" },
	{ LOCATE_SI, "SI", "Slovenia" },
	{ LOCATE_SJ, "SJ", "Svalbard & Jan Mayen" },
	{ LOCATE_SK, "SK", "Slovakia" },
	{ LOCATE_SL, "SL", "Sierra Leone" },
	{ LOCATE_SM, "SM", "San Marino" },
	{ LOCATE_SN, "SN", "Senegal" },
	{ LOCATE_SO, "SO", "Somalia" },
	{ LOCATE_SR, "SR", "Suriname" },
	{ LOCATE_SS, "SS", "South Sudan" },
	{ LOCATE_ST, "ST", "Sao Tome & Principe" },
	{ LOCATE_SV, "SV", "El Salvador" },
	{ LOCATE_SX, "SX", "St Maarten (Dutch part)" },
	{ LOCATE_SY, "SY", "Syria" },
	{ LOCATE_SZ, "SZ", "Swaziland" },
	{ LOCATE_TC, "TC", "Turks & Caicos Is" },
	{ LOCATE_TD, "TD", "Chad" },
	{ LOCATE_TF, "TF", "French Southern & Antarctic Lands" },
	{ LOCATE_TG, "TG", "Togo" },
	{ LOCATE_TH, "TH", "Thailand" },
	{ LOCATE_TJ, "TJ", "Tajikistan" },
	{ LOCATE_TK, "TK", "Tokelau" },
	{ LOCATE_TL, "TL", "East Timor" },
	{ LOCATE_TM, "TM", "Turkmenistan" },
	{ LOCATE_TN, "TN", "Tunisia" },
	{ LOCATE_TO, "TO", "Tonga" },
	{ LOCATE_TR, "TR", "Turkey" },
	{ LOCATE_TT, "TT", "Trinidad & Tobago" },
	{ LOCATE_TV, "TV", "Tuvalu" },
	{ LOCATE_TW, "TW", "Taiwan" },
	{ LOCATE_TZ, "TZ", "Tanzania" },
	{ LOCATE_UA, "UA", "Ukraine" },
	{ LOCATE_UG, "UG", "Uganda" },
	{ LOCATE_UM, "UM", "US minor outlying islands" },
	{ LOCATE_US, "US", "United States" },
	{ LOCATE_UY, "UY", "Uruguay" },
	{ LOCATE_UZ, "UZ", "Uzbekistan" },
	{ LOCATE_VA, "VA", "Vatican City" },
	{ LOCATE_VC, "VC", "St Vincent" },
	{ LOCATE_VE, "VE", "Venezuela" },
	{ LOCATE_VG, "VG", "Virgin Islands (UK)" },
	{ LOCATE_VI, "VI", "Virgin Islands (US)" },
	{ LOCATE_VN, "VN", "Vietnam" },
	{ LOCATE_VU, "VU", "Vanuatu" },
	{ LOCATE_WF, "WF", "Wallis & Futuna" },
	{ LOCATE_WS, "WS", "Samoa (western)" },
	{ LOCATE_XX, "XX", "undefined" },
	{ LOCATE_YE, "YE", "Yemen" },
	{ LOCATE_YT, "YT", "Mayotte" },
	{ LOCATE_ZA, "ZA", "South Africa" },
	{ LOCATE_ZM, "ZM", "Zambia" },
	{ LOCATE_ZW, "ZW", "Zimbabwe" },
};

/*
 * End of autogenerated section. YOU MAY CONTINUE.
 */

struct peak_locates {
	struct peak_locate *mem;
	size_t count;
};

unsigned int
peak_locate_get(struct peak_locates *self, const struct netaddr *me)
{
	unsigned int ret = LOCATE_UNKNOWN;
	struct peak_locate *elm;
	struct peak_locate ref;

	if (self->count) {
		/*
		 * We know min and max match, but locatecmp
		 * doesn't know about it, so pass it on.
		 */
		ref.min = *me;
		ref.max = *me;

		elm = bsearch(&ref, self->mem, self->count,
		    sizeof(*self->mem), peak_locate_cmp);

		/* return result or undefined since we went looking */
		ret = elm ? elm->location : LOCATE_XX;
	}

	return (ret);
}

void
peak_locate_exit(struct peak_locates *self)
{
	if (self) {
		free(self->mem);
		free(self);
	}
}

struct peak_locates *
peak_locate_init(const char *file)
{
	struct peak_locate_hdr hdr;
	struct peak_locates *ret;
	struct peak_locate ref;
	unsigned int i;
	int fd;

	ret = malloc(sizeof(*ret));
	if (!ret) {
		alert("could not allocate memory\n");
		return (NULL);
	}

	ret->mem = NULL;
	ret->count = 0;

	if (!file) {
		file = LOCATE_DEFAULT;
	}

	fd = open(file, O_RDONLY);
	if (fd < 0) {
		warning("could not open file `%s'\n", file);
		return (ret);
	}

	if (read(fd, &hdr, sizeof(hdr)) != sizeof(hdr)) {
		warning("file header not available\n");
		goto peak_locate_init_out;
	}

	if (hdr.magic != LOCATE_MAGIC) {
		warning("file magic mismatch\n");
		goto peak_locate_init_out;
	}

	if (hdr.revision != LOCATE_REVISION) {
		warning("file revision mismatch: got %u, want %u\n",
		    hdr.revision, LOCATE_REVISION);
		goto peak_locate_init_out;
	}

	if (!hdr.count) {
		goto peak_locate_init_out;
	}

	ret->mem = reallocarray(NULL, hdr.count, sizeof(*ret->mem));
	if (!ret->mem) {
		warning("memory allocation failed\n");
		goto peak_locate_init_out;
	}

	for (i = 0; i < hdr.count; ++i) {
		if (read(fd, &ref, sizeof(ref)) != sizeof(ref)) {
			warning("file not complete\n");
			free(ret->mem);
			ret->mem = NULL;
			goto peak_locate_init_out;
		}

		memcpy(&ret->mem[i], &ref, sizeof(ref));
	}

	ret->count = hdr.count;

peak_locate_init_out:

	close(fd);

	if (ret->count) {
		warning("successfully loaded %u locations\n", hdr.count);
	}

	return (ret);
}

static int
kw_cmp(const void *x, const void *yy)
{
        const struct locate_item *y = yy;

        return (strcmp(x, y->name));
}

unsigned int
peak_locate_number(const char *name)
{
	struct locate_item *location;

	location = bsearch(name, locate_items, lengthof(locate_items),
	    sizeof(locate_items[0]), kw_cmp);
	if (!location) {
		return (LOCATE_UNKNOWN);
	}

	return (location->guid);
}


const char *
peak_locate_name(const unsigned int number)
{
	if (number >= LOCATE_MAX) {
		return (NULL);
	}

	return (locate_items[number].name);
}

const char *
peak_locate_desc(const unsigned int number)
{
	if (number >= LOCATE_MAX) {
		return (NULL);
	}

	return (locate_items[number].desc);
}
